### ISSUE TITLE
有Uncaught Error: Dynamic require报错.

### ISSUE THREAD

**Issue by XiaoYong1995** [element-plus/vite-plugin-element-plus#13]
Uncaught Error: Dynamic require of "D:/xxxxx/node_modules/element-plus/theme-chalk/base.css" is not supported

**Comment by XiaoYong1995** [comment]
![image](https://user-images.githubusercontent.com/24826683/131818043-859833f1-915e-40f1-aa63-b1cde53642e3.png)

**Comment by btea** [comment]
信息太少，可以提供一个复现的地址或者描述一下具体的操作步骤~

**Comment by XiaoYong1995** [comment]
> 信息太少，可以提供一个复现的地址或者描述一下具体的操作步骤~

可能是我代码的问题,昨天改了下又好了..
